ARG VER=latest

FROM ubchemica/psi4-docker-utils:base-$VER

SHELL ["conda", "run", "--live-stream", "-n", "p4env", "/bin/bash", "-c"]

# Also install a few utility libraries if they're not already installed (at least numpy SHOULD be)
RUN conda remove --offline libint

WORKDIR /home/ubuntu/work
